### ISSUE TITLE
Q1.2: load examples and store results

### ISSUE THREAD

**Issue by Curlykonda** [JacobPfau/introspective-self-consistency#46]
# TODO
- [x] load examples that were consistent/selected and stored in previous experiment
- [x] handle multiple sub-token for obtaining logprobs (see TODO in code)
- [x] integrate Hydra
- [x] run eval for OpenAI models
- [x] store results of test-passing and possible responses
