### ISSUE TITLE
State set of possible functions in prompt

### ISSUE THREAD

**Issue by Curlykonda** [JacobPfau/introspective-self-consistency#63]
# Problem to solve
Models currently have access to the full set of function that could generate sequences. Hence ambiguity metrics are confounded by possible functions the model knows about.

# Tasks
- [x] add methods to collect and format function space
- [x] prepend function space to prompts
- [x] add flag to add/not add function space
