### ISSUE TITLE
Debug base change experiments

### ISSUE THREAD

**Issue by Curlykonda** [JacobPfau/introspective-self-consistency#68]
# Problem to Solve
We need to ensure that the experiments for base changes can be run and integrate with the refactored codebase. 

There's also some code in `prompt_generation/robustness_checks` that Henning didn't know how to integrate properly. To keep effort low, you don't need to re-write it but check that it performs the expected functionality and try to re-use methods and abstractions from other modules (e.g., load prompts from txt files)

**Goal:** able to run task `compute_dependence_with_base_changes` with hydra config and sweep over

In a separate PR, we wish to do the actual runs and add the results to keep PRs small.

# Tasks
- [x] check if there redudancy could be removed, i.e. where are functions that do basically the same thing?
- [x] debug experiments 
- [x] remove unused code that is currently in `prompt_generation/robustness_checks`
- [x] test that single and multirun of task `compute_dependence_with_base_changes` work
- [ ] update README
- [ ] create separate PR for runs and results
