### ISSUE TITLE
Re-run Q2 experiments

### ISSUE THREAD

**Issue by Curlykonda** [JacobPfau/introspective-self-consistency#72]
# Tasks
- [x] Q2.1: sweep over invalid_fn_types and num_shots
- [x] Q2.1: sweep over models and configs
- [x] eval and plot Q2.1
- [x] eval and plot Q2.2
- [x] update plots and analysis in paper
- [x] push results to repo
