### ISSUE TITLE
Add control experiment with same few-shot samples

### ISSUE THREAD

**Issue by Curlykonda** [JacobPfau/introspective-self-consistency#77]
# Problem
Non-deterministic behaviour of GPT models and varying few-shot examples might already account for inconsistencies. Run a control experiment to check that.

# Tasks
- [ ] sample few shot examples
- [ ] store them in data/control_experiment
- [ ] load and use them for completion and explanation consistency (Q0)
