### ISSUE TITLE
Create POC that evaluates consistency AmbiBench completions

### ISSUE THREAD

**Issue by Curlykonda** [JacobPfau/introspective-self-consistency#8]
# Problem
We wish to use the AmbiBench dataset to prompt and evaluate LLMs wrt. consistency under ambiguity. We need an interface to generate various AmbiBench examples, construct (few-shot) prompts, query a ChatGPT, and evaluate consistency.
Furthermore, we want to change the task, from the original "output X if the withheld category is present" towards generating an explanation or rule. When the model gives an explanation, we want to evaluate whether it's consistent with the sequence and the mode's own prediction. 

# Task
- [ ] implement interface to generate examples for our pipeline
- [ ] create few-shot prompt template
- [ ] create consistency metric
- [ ] (bonus) 

# Acceptance Criteria
- [ ] simple script/interface to generate AmbiBench examples and prompt
- [ ] simple script to compute consistency metric
